### ISSUE TITLE
Seed project with basic front-end dev tooling and structure

### ISSUE THREAD

**Issue by amhester** [amhester/GameOff2019#5]
Will be good to have a basic set of starting tools and frameworks in place, as well as project structure so we can hit the ground running once we start actually implementing screens and game logic.

**Comment by amhester** [comment]
I think this is pretty much done already, right @djragsdale ?

**Comment by djragsdale** [comment]
Yep, I went ahead and merged the feature/webpack-build branch into master at 3f948c1
